Repository CLIPPER-1st/Gojip-CLIPPER-1st-BE, pull requests merged in 2024-02, with the labels that each got.

#3 [Feat/1] swagger 적용
  build.gradle
  src/main/java/com/example/gojipserver/global/config/OpenApiConfig.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/java/com/example/gojipserver/global/config/security/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/gojipserver/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/gojipserver/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/gojipserver/global/entity/ExpireTime.java
  src/main/resources/application.yml
Labels: feat

#5 [Feat/3] CheckList 엔티티 설계 및 s3 연동
  .gitignore
  build.gradle
  src/main/java/com/example/gojipserver/domain/address/entity/Address.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/BathRoomStatus.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/HotWater.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/ShowerHead.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/Sink.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/Tile.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/Toilet.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/WashStand.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/cost/Cost.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/cost/ManagementCostIncludeOption.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/option/InnerOption.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/option/OuterOption.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomcondition/Building.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomcondition/Noise.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomcondition/RoomCondition.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomstatus/Boiler.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomstatus/Light.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomstatus/RoomStatus.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/CheckListRepository.java
  src/main/java/com/example/gojipserver/domain/collection/entity/Collection.java
  src/main/java/com/example/gojipserver/domain/img/entity/RoomImage.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
  src/main/java/com/example/gojipserver/global/aws/config/AwsS3Config.java
  src/main/java/com/example/gojipserver/global/aws/controller/AmazonS3Controller.java
  src/main/java/com/example/gojipserver/global/aws/service/AwsS3Service.java
  src/main/java/com/example/gojipserver/global/response/ApiResponse.java
  src/main/java/com/example/gojipserver/global/response/StatusEnum.java
  src/main/resources/application-local.yml
Labels: feat

#10 [Feat/9] UserPrincipal 권한 수정
  src/main/java/com/example/gojipserver/domain/oauth2/service/CustomUserDetailsService.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/java/com/example/gojipserver/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/gojipserver/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/gojipserver/global/oauth2/entity/AuthProvider.java
  src/main/java/com/example/gojipserver/global/oauth2/entity/UserPrincipal.java
  src/main/java/com/example/gojipserver/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/gojipserver/global/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/example/gojipserver/global/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/example/gojipserver/global/oauth2/userInfo/OAuth2UserInfoFactory.java
Labels: feat, fix

#11 [Feat/7] 다대다관계 매핑
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/checklist_collection/entity/CheckListCollection.java
  src/main/java/com/example/gojipserver/domain/collection/entity/Collection.java
  src/main/java/com/example/gojipserver/global/response/ApiResponse.java
Labels: feat, fix

#14 [Fix/10] Collection -> CheckList 참조 에러 해결
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/collection/entity/Collection.java
Labels: fix, refactor

#18 [Feat/11] 컬렉션 조회 API 구현
  src/main/java/com/example/gojipserver/domain/collection/controller/CollectionController.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionResponseDto.java
  src/main/java/com/example/gojipserver/domain/collection/repository/CollectionRepository.java
  src/main/java/com/example/gojipserver/domain/collection/service/CollectionService.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/java/com/example/gojipserver/global/response/ApiResponse.java
  src/main/resources/application-local.yml
  src/main/resources/application-swagger.yml
Labels: feat, fix, refactor

#20 [Feat/12] 이미지 등록 API
  build.gradle
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListSaveDto.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/collection/entity/Collection.java
  src/main/java/com/example/gojipserver/domain/roomimage/controller/RoomImageController.java
  src/main/java/com/example/gojipserver/domain/roomimage/entity/RoomImage.java
  src/main/java/com/example/gojipserver/domain/roomimage/repository/RoomImageRepository.java
  src/main/java/com/example/gojipserver/domain/roomimage/service/ImageService.java
  src/main/java/com/example/gojipserver/global/config/OpenApiConfig.java
  src/main/java/com/example/gojipserver/global/oauth2/entity/AuthProvider.java
  src/main/java/com/example/gojipserver/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/gojipserver/global/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/example/gojipserver/global/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/example/gojipserver/global/oauth2/userInfo/OAuth2UserInfoFactory.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feat

#22 [Feat/17] Kakao restAPI적용 & refreshToken 저장
  build.gradle
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/oauth2/controller/KakaoController.java
  src/main/java/com/example/gojipserver/domain/oauth2/dto/KakaoUserInfoDto.java
  src/main/java/com/example/gojipserver/domain/oauth2/dto/UserDto.java
  src/main/java/com/example/gojipserver/domain/oauth2/entity/AuthProvider.java
  src/main/java/com/example/gojipserver/domain/oauth2/service/CustomUserDetailsService.java
  src/main/java/com/example/gojipserver/domain/oauth2/service/KakaoService.java
  src/main/java/com/example/gojipserver/domain/oauth2/service/OAuthService.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/OAuth2UserInfoFactory.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/java/com/example/gojipserver/global/config/WebClientConfig.java
  src/main/java/com/example/gojipserver/global/config/redis/RedisConfig.java
  src/main/java/com/example/gojipserver/global/config/redis/entity/RefreshToken.java
  src/main/java/com/example/gojipserver/global/config/redis/repository/RefreshTokenRepository.java
  src/main/java/com/example/gojipserver/global/config/security/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/gojipserver/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/gojipserver/global/oauth2/service/CustomOAuth2UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-jwt.yml
Labels: feat, refactor

#23 [Feat/13] 체크리스트 등록 API 구현
  src/main/java/com/example/gojipserver/GojipServerApplication.java
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListSaveDto.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/BathRoomStatus.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/HotWater.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/ShowerHead.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/Sink.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/Tile.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/Toilet.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/bathroomstatus/WashStand.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/cost/Cost.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/cost/ManagementCostIncludeOption.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/option/InnerOption.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/option/OuterOption.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomcondition/Building.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomcondition/RoomCondition.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomstatus/Boiler.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomstatus/Light.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/roomstatus/RoomStatus.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/checklist_collection/entity/CheckListCollection.java
  src/main/java/com/example/gojipserver/domain/checklist_collection/repository/CheckListCollectionRepository.java
  src/main/java/com/example/gojipserver/domain/collection/controller/CollectionController.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionResponseDto.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionSaveDto.java
  src/main/java/com/example/gojipserver/domain/collection/entity/Collection.java
  src/main/java/com/example/gojipserver/domain/roomaddress/entity/RoomAddress.java
  src/main/java/com/example/gojipserver/domain/roomaddress/repository/RoomAddressRepository.java
  src/main/java/com/example/gojipserver/domain/roomimage/dto/RoomImageSaveDto.java
  src/main/java/com/example/gojipserver/domain/roomimage/entity/RoomImage.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
  src/main/java/com/example/gojipserver/global/auditing/BaseTimeEntity.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-swagger.yml
  src/main/resources/application.yml
Labels: feat, refactor

#25 Feat/21 이미지 수정, 삭제 API
  build.gradle
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/oauth2/entity/AuthProvider.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/OAuth2UserInfoFactory.java
  src/main/java/com/example/gojipserver/domain/roomimage/controller/RoomImageController.java
  src/main/java/com/example/gojipserver/domain/roomimage/dto/RoomImageSaveDto.java
  src/main/java/com/example/gojipserver/domain/roomimage/entity/RoomImage.java
  src/main/java/com/example/gojipserver/domain/roomimage/repository/RoomImageRepository.java
  src/main/java/com/example/gojipserver/domain/roomimage/service/ImageService.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: feat

#28 [Feat/27] 도커파일 적용
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: feat

#29 [Fix/27] 트랜잭션 에러
  src/main/java/com/example/gojipserver/domain/oauth2/service/KakaoService.java
  src/main/resources/application-local.yml
Labels: fix

#30 [Feat/24] 체크리스트 삭제, 컬렉션 수정 API, 예외 처리
  build.gradle
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListOneGetDto.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListSaveDto.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/checklist_collection/repository/CheckListCollectionRepository.java
  src/main/java/com/example/gojipserver/domain/collection/controller/CollectionController.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionUpdateDto.java
  src/main/java/com/example/gojipserver/domain/collection/entity/Collection.java
  src/main/java/com/example/gojipserver/domain/collection/repository/CollectionRepository.java
  src/main/java/com/example/gojipserver/domain/collection/service/CollectionService.java
  src/main/java/com/example/gojipserver/global/exception/DuplicateException.java
  src/main/java/com/example/gojipserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/gojipserver/global/exception/NotOwnerException.java
  src/main/java/com/example/gojipserver/global/response/ApiResponse.java
  src/main/java/com/example/gojipserver/global/response/StatusEnum.java
  src/main/resources/application-local.yml
Labels: feat

#32 Feat/26 주소 등록 API
  build.gradle
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListResponseDto.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/roomaddress/controller/RoomAddressController.java
  src/main/java/com/example/gojipserver/domain/roomaddress/dto/RoomAddressResponseDto.java
  src/main/java/com/example/gojipserver/domain/roomaddress/dto/RoomAddressSaveDto.java
  src/main/java/com/example/gojipserver/domain/roomaddress/entity/Coordinates.java
  src/main/java/com/example/gojipserver/domain/roomaddress/entity/RoomAddress.java
  src/main/java/com/example/gojipserver/domain/roomaddress/service/RoomAddressService.java
  src/main/java/com/example/gojipserver/domain/roomimage/controller/RoomImageController.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/resources/application-kakao.yml
  src/main/resources/application.yml
Labels: feat

#34 [Feat/17] 카카오 로그아웃 & 토큰 갱신 & 토큰에러처리
  Dockerfile
  src/main/java/com/example/gojipserver/domain/oauth2/controller/KakaoController.java
  src/main/java/com/example/gojipserver/domain/oauth2/dto/UserDto.java
  src/main/java/com/example/gojipserver/domain/oauth2/entity/AuthProvider.java
  src/main/java/com/example/gojipserver/domain/oauth2/service/KakaoService.java
  src/main/java/com/example/gojipserver/domain/oauth2/service/OAuthService.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/example/gojipserver/domain/oauth2/userInfo/OAuth2UserInfoFactory.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
  src/main/java/com/example/gojipserver/global/config/OpenApiConfig.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/java/com/example/gojipserver/global/config/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/example/gojipserver/global/config/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/gojipserver/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/gojipserver/global/config/jwt/JwtTokenProvider.java
  src/main/java/com/example/gojipserver/global/config/redis/entity/AccessToken.java
  src/main/java/com/example/gojipserver/global/config/redis/repository/AccessTokenRepository.java
  src/main/java/com/example/gojipserver/global/response/ErrorCode.java
Labels: feat, refactor

#35 Feat/33 체크리스트 단일 조회 API
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListAllGetDto.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListOneGetDto.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/roomaddress/controller/RoomAddressController.java
  src/main/java/com/example/gojipserver/domain/roomaddress/service/RoomAddressService.java
  src/main/resources/application-kakao.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feat

#39 [Feat/Test] GitAction CI/CD
  .github/workflows/main.yml
Labels: feat

#42 feat: cors 설정
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
Labels: feat

#44 Feat/43 체크리스트 전체 조회 API, 주소 등록 API 수정
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListAllGetDto.java
  src/main/java/com/example/gojipserver/domain/roomaddress/controller/RoomAddressController.java
  src/main/java/com/example/gojipserver/domain/roomaddress/dto/RoomAddressResponseDto.java
Labels: feat, fix
